workflows:
  android-workflow:
    name: Build Charging Timer APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - rishabhnahata1@gmail.com
