workflows:
  android-build:
    max_build_duration: 60
    environment:
      vars: {}
    working_directory: ChargingTimerApp
    scripts:
      - name: Build Debug APK
        script: gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rishabhnahata1@gmail.com
