workflows:
  android-workflow:
    name: Build Charging Timer APK
    max_build_duration: 60
    environment:
      vars: {}
     scripts:
      - name: Set Gradle wrapper as executable
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - ChargingTimerApp/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rishabhnahata1@gmail.com
